# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao_app', '0002_eleitor_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='voto',
        ),
    ]
